from youtube_transcript_api import YouTubeTranscriptApi
import re

def extract_video_id(url_or_id: str) -> str:
    """Extract the video ID from a YouTube URL or return the ID if it matches the pattern."""
    if len(url_or_id) == 11 and re.match(r'^[a-zA-Z0-9_-]{11}$', url_or_id):
        return url_or_id
    
    # Regular expressions for different YouTube URL formats
    patterns = [
        r'(?:v=|\/)([0-9A-Za-z_-]{11}).*',
        r'youtu\.be\/([0-9A-Za-z_-]{11})',
        r'youtube\.com\/shorts\/([0-9A-Za-z_-]{11})',
        r'youtube\.com\/embed\/([0-9A-Za-z_-]{11})'
    ]
    
    for pattern in patterns:
        match = re.search(pattern, url_or_id)
        if match:
            return match.group(1)
            
    raise ValueError("Invalid YouTube URL or Video ID")

def get_transcript(video_id: str) -> str:
    """Fetch the transcript for a given YouTube video ID and return it as a string."""
    try:
        # Fetch the transcript (defaulting to manually created or autogenerated)
        transcript_list = YouTubeTranscriptApi.get_transcript(video_id)
        
        # Combine the text parts into a single string
        full_transcript = " ".join([item['text'] for item in transcript_list])
        return full_transcript
        
    except Exception as e:
        raise Exception(f"Could not retrieve transcript: {str(e)}")

# Example usage (for testing)
if __name__ == "__main__":
    url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    try:
        vid = extract_video_id(url)
        print(f"Video ID: {vid}")
        # print(get_transcript(vid))
    except Exception as e:
        print(e)
